language: c
script:
    - make clean all
    - make test
    - (cd examples && make clean all)
    - (cd examples/reply/ && ./test_reply_01.sh)
    - (cd examples/reply/ && ./test_reply_02.sh)
    - (cd examples/reply/ && ./test_reply_03.sh)
    - (cd examples/reply/ && ./test_reply_04.sh)
    - (cd examples/forward/ && ./test_forward_01.sh)
    - (cd examples/stun/ && ./test_stun_01.sh)
    - (cd examples/sfetch/ && ./test_sfetch_01.sh)
    - (cd examples/sreply/ && ./test_sreply_01.sh)
    - (cd examples/sreply/ && ./test_sreply_02.sh)
    - (cd examples/sreply/ && ./test_sreply_03.sh)

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install openssl libev-dev netcat pv socat -qq
    - wget http://downloads.sourceforge.net/project/check/check/0.10.0/check-0.10.0.tar.gz -O /tmp/libcheck.tar.gz
    - tar xf /tmp/libcheck.tar.gz -C /tmp
    - (cd /tmp/check-0.10.0/ && ./configure --prefix=/usr && make && sudo make install)
    
before_script:
    - cp doc/travis.rules.site rules.site
