language: c
script:
    - make clean all
    - make test

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install check openssl openssl-dev libev libev-dev -qq
    
before_script:
    - cp doc/travis.rules.site rules.site
