language: c

compiler:
    - gcc

script:
    - make clean
    - USE_COVERAGE=1 make all
    - USE_COVERAGE=1 make test
    - USE_COVERAGE=1 make examples
    - (cd examples/reply/ && ./test_reply_01.sh)
    - (cd examples/reply/ && ./test_reply_02.sh)
    - (cd examples/reply/ && ./test_reply_03.sh)
    - (cd examples/reply/ && ./test_reply_04.sh)
    - (cd examples/forward/ && ./test_forward_01.sh)
    - (cd examples/stun/ && ./test_stun_01.sh)
    - (cd examples/sreply/ && ./test_sreply_01.sh)
    - (cd examples/sreply/ && ./test_sreply_02.sh)
    - (cd examples/sreply/ && ./test_sreply_03.sh)
#    - (cd examples/sfetch/ && ./test_sfetch_01.sh)
    - (cd examples/http_server/ && ./test_httpserver_01.sh)

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install openssl libev-dev netcat pv socat hugepages apache2-utils -qq
    - wget http://downloads.sourceforge.net/project/check/check/0.10.0/check-0.10.0.tar.gz -O /tmp/libcheck.tar.gz
    - tar xf /tmp/libcheck.tar.gz -C /tmp
    - (cd /tmp/check-0.10.0/ && ./configure --prefix=/usr && make && sudo make install)
    
before_script:
    - cp doc/travis.rules.site rules.site
    - sudo hugeadm --pool-pages-min DEFAULT:2

notifications:
    slack: teskalabs:6pYgZhD2AwcKGkeuNbS4IH4s

after_success:
    - USE_COVERAGE=1 make coverage
    - (cd ./src && bash <(curl -s https://codecov.io/bash) -X gcov )
