LIB=libsccmn.a

OBJS=\
	boolean.o \
	base32.o \
	fd.o \
	ini.o \
	config.o \
	log.o \
	daemon.o \
	sock/listener.o \
	sock/stream.o \
	mempool/frame.o \
	mempool/pool.o \
	mempool/zone.o \
	context.o \
	cols/list.o \

all: $(LIB)

ROOTDIR=..
include $(ROOTDIR)/rules.make
